config/routes.rb
Rails.application.routes.draw do

  get 'exhibits/levels'
  get 'exhibits/exhibit'
  get 'sessions/new'
  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'levels' => 'exhibits#levels'
  get 'exhibit' => 'exhibits#exhibit'
  get 'exhibit/:id' => 'exhibits#exhibit', as: :exhibit_page
  get 'display' => 'exhibits#exhibit'
  get 'exhibits/:ex/display/:id' => 'exhibits#display', as: :display_page
  get 'signup' 	=> 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
end

app/models/displays.rb
class Displays < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # using simplified regex, duplicated dots (.) are allowed
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	# Returns the hash digest of the given string
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  def levels
  end

  def exhibit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Welcome to Culture Companion!"
			redirect_to @user
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# returns the full title on a per-page basis
	def full_title(page_title = '')
		base_title = "Te Arahi"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

	def parse_exhibit(exhibitId = '', type = '')
		hash = JSON.parse(File.read('public/assets/' + exhibitId + '.json'))
		hash[type]
	end
	
	def parse_display(exhibitId = '', displayId = '', type = '')
		hash = JSON.parse(File.read('public/assets/' + exhibitId + '/' + displayId + '.json'))
		hash[type]
	end
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=200"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/exhibits/display.html.erb
<% exhibit_id = params[:ex] %>
<% display_id = params[:id] %>
<% provide(:title, parse_display(exhibit_id, display_id, 'title')) %>

<div class="center jumbotron" style="background: url(<%= asset_path('display-images/' + display_id + '.jpg') %>); margin-bottom: 5px">
	<h1 style="color: white !important;"><%= parse_display(exhibit_id, display_id, 'title') %></h1>
	<h2 style="color: white !important;"><%= parse_display(exhibit_id, display_id, 'subText') %></h2>
</div>

<p style="background: rgba(255, 255, 255, 0.6); text-align: center; padding: 5px;">Exhibit: <span class='text-muted'><%= parse_display(exhibit_id, display_id, 'exhibit') %></span></p>
<a href='#' class="btn btn-wide btn-green" style="margin-bottom: 10px;"><span class="glyphicon glyphicon-user"></span> Save Display</a>

<% para = parse_display(exhibit_id, display_id, 'paragraph') %>
	
<div  style="background-color: rgba(255, 255, 255, 0.4); padding: 10px;"><% para.each do |para| %>
	<% unless para['title'] == 'NULL' %>
		<h3><%= para['title'] %></h3>
	<% end %>
	<p><%= para['text'] %></p>
<% end %></div>

<footer class="footer">
  <div class="row">
    <div class="col-xs-4">
      <span class="glyphicon glyphicon-chevron-left"></span> <%= link_to "Back", exhibit_page_path(exhibit_id) %>
    </div><div class="col-xs-4">
      	<span class="glyphicon glyphicon-user"></span>
    	<% if logged_in? %>
			<%= link_to "Profile", current_user %>
		<% else %>
			<%= link_to "Log In", login_path %>
		<% end %>
    </div><div class="col-xs-4">
      <span class="glyphicon glyphicon-question-sign"></span> <%= link_to "Help", help_path %>
    </div>
</footer>

app/views/exhibits/exhibit.html.erb
<% exhibit_id = params[:id] %>
<% provide(:title, parse_exhibit(exhibit_id, 'title')) %>

<div class="exhibit-header" style="background: url('<%= image_path('exhibit-images/' + exhibit_id + '.jpg') %>');">
	<h1><%= parse_exhibit(exhibit_id, 'title') %></h1>
	<h2 style="margin-bottom: 0px;"><%= parse_exhibit(exhibit_id, 'subText') %></h2>
</div>

<div class="row info-box">
	<div class="col-xs-3">
		<p><span class="glyphicon glyphicon-info glyphicon-map-marker"></span><%= parse_exhibit(exhibit_id, 'where') %></p>
	</div><div class="col-xs-3" style="border-right: 1px solid #333; border-left: 1px solid #333;">
		<p><span class="glyphicon glyphicon-info glyphicon-time"></span><%= parse_exhibit(exhibit_id, 'when') %></p>
	</div><div class="col-xs-3" style="border-right: 1px solid #333;">
		<p><span class="glyphicon glyphicon-info glyphicon-usd"></span><%= parse_exhibit(exhibit_id, 'cost') %></p>
	</div><div class="col-xs-3">
		<p><span class="glyphicon glyphicon-info glyphicon-tags"></span><%= parse_exhibit(exhibit_id, 'type') %></p>
	</div>
</div>

<div class="q-wrapper">
	<h3>Estimated Wait Time:</h3>
	<h1 class="q-timer">Approx. 2min</h1>
	<p class="q-help"><%= link_to 'What is this?', about_path(anchor: "q") %></p>
</div>
	
<div class='row'>
	<div class='col-md-9'>
		<!-- Displays -->
		<% if File.directory?('public/assets/' + exhibit_id) %>
			<p><a class="btn btn-wide btn-green" data-toggle="collapse" href="#displays" aria-expanded="false">Displays <span class="glyphicon glyphicon-chevron-down"></span></a></p>
			<div id="displays" class="collapse">
			<% Dir.foreach('public/assets/' + exhibit_id) do |display| %>
				<% unless display == '.' or display == '..' or display == 'display1.json' or display == 'display2.json' or display == 'display3.json' or display == 'display4.json' %>
					<% display_id = display[0..-(File.extname(display).length + 1)] %>
					<% display_name = parse_display(exhibit_id, display_id, 'title') %>
				 	<p><%= link_to display_name + ' »', display_page_path(exhibit_id, display_id), class: "btn btn-wide btn-green-outline" %></p>
			 	<% end %>
			<% end %>
			</div>
		<% else %>
			<p style="text-align: center; background-color: rgba(255, 255, 255, 0.6)">This exhibit is not yet NFC enabled. Sorry for any inconvenience.</p>
		<% end %>
	</div>

	<div class='col-md-3'>

		<% para = parse_exhibit(exhibit_id, 'paragraph') %>
		<% para.each do |para| %>
			<% unless para['title'] == 'NULL' %>
				<h3><%= para['title'] %></h3>
			<% end %>
			<p style="background-color: rgba(255, 255, 255, 0.4); padding: 10px;"><%= para['text'] %></p>
		<% end %>
	</div>
</div>

<footer class="footer">
  <div class="row">
    <div class="col-xs-4">
      <span class="glyphicon glyphicon-chevron-left"></span> <%= link_to "Back", levels_path %>
    </div><div class="col-xs-4">
      	<span class="glyphicon glyphicon-user"></span>
    	<% if logged_in? %>
			<%= link_to "Profile", current_user %>
		<% else %>
			<%= link_to "Log In", login_path %>
		<% end %>
    </div><div class="col-xs-4">
      <span class="glyphicon glyphicon-question-sign"></span> <%= link_to "Help", help_path %>
    </div>
</footer>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class="col-xs-4">
      <span class="glyphicon glyphicon-chevron-left"></span> Back
    </div><div class="col-xs-4">
      	<span class="glyphicon glyphicon-user"></span>

    	<% if logged_in? %>
			<%= link_to "Profile", current_user %>
		<% else %>
			<%= link_to "Log In", login_path %>
		<% end %>
    </div><div class="col-xs-4">
      <span class="glyphicon glyphicon-question-sign"></span> Help
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-default">
	<nav>
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Te Arahi", root_path, id: "logo" %>
			</div>

			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
					<% if logged_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li class="divider"></li>
							<li><%= link_to "Log out", logout_path, method: "delete" %></li>
						</ul>
					</li>
					<% else %>
					<li><%= link_to "Log in", login_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,400italic,700|Roboto+Slab:400,700' rel='stylesheet' type='text/css'>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>
		<!--<%= debug(params) if Rails.env.development? %>-->
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>So what's all of this about, then?</h1>
<p>Glad you asked! Te Arahi is a 'Web-based Companion App' for our Te Papa exhibits. In other words, it's a website that can accompany you on your smart phone, tablet, or laptop while you look around Te Papa, providing extra information, videos, audio snippets and additional material to complete your Te Papa experience. It can even make suggestions on what you might want to check out next!</p>

<h1>How does it work?</h1>
<p>Te Arahi uses a range of different technologies to make it as easy as possible for you to get more information about each part of an exhibition. You'll find NFC tags, QR codes, and unique ID codes scattered around Te Papa which will take you to each different section of the web site.</p>

<!-- DIVE DEEPER -->
<h1>But why should you bother?</h1>
<p>Have you ever found a display in a museum that really gets you thinking? Something that interests you, something that you want to know more about? When we put together an exhibit, we selected some of the most important parts to show you, but there's so much more beneath the surface which we can't possibly fit! More stories, pictures, audio recordings and videos than you can sink your teeth into, and all in one easy-to-use online repository, ready at your fingertips for you to dive in.</p>

<h1>How can we make your experience more personal?</h1>
<p>When you decide to sign up for a Te Arahi account, one of the things that we recommend you do first is to take a short survey. The survey will ask you a few easy questions, such as how old you are and what you're interests are. This information will be used not only to help us make your experience better in the future, but also to curate your <i>Recommended</i> section - when you're ready to move onto something else, we can provide some handy suggestions on what we think you might like.</p>

<h1 id="q">What is Q?</h1>
<p>Q is your friend to avoid the lines to get in to see exhibits! Te Papa allocates you with a small device that fits in the palm of your hand. These devices allow you to 'log on' to an exhibitions queue. The device shows the number you are in the line and countdown for the particular exhibition you choose to see. The device will give alerts and notifications if the exhibition is running late or early. A GPS sensor is located on the device tracking you through the museum and directing you back to the exhibition you are queued for. This saves you waiting in lines allowing you to see other exhibitions. Pick up this device from Level 2 reception!</p>

<div style="width: 100%"><iframe src="https://player.vimeo.com/video/97501818" width="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>

<h1>What are you waiting for?</h1>
<p>That's all you need to know for now! If you like the sound of an easy-to-use online tour guide to expand and personalise your experience at Te Papa, sign up for a completely free account now <%= link_to "sign up for a completely free account now", signup_path %>!</p>

<footer class="footer">
  <div class="row">
    <div class="col-xs-4">
    </div><div class="col-xs-4">
    	<span class="glyphicon glyphicon-home"></span> <%= link_to "Home", root_path %>
    </div><div class="col-xs-4">
    </div>
</footer>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>How does it work?</h1>
<p>My Te Papa uses a range of different technologies to make it as easy as possible for you to get more information about each part of an exhibition. You'll find NFC tags, QR codes, and unique ID codes scattered around Te Papa which will take you to each different section of the web site.</p>

<h1>How do I use NFC?</h1>
<p>NFC (Near Field Communication) is a technology that allows data to be passed wirelessly between an RFID tag (a sticker on a display) and your phone. If you have an NFC compatible device, turn NFC on in the settings then press your phone up against the poster, on the spot highlighted by the NFC directions. Your phone will open the app right at the place where you need it!</p>

<h1>How do I use QR Codes</h1>
<p>QR Codes are like barcodes which you can scan with your phone. Download a free QR reader from the app store onto your phone, open the app, then arrange the QR code on the display between the markings on your camera. Your phone will prompt you to open a web page, which will open to the display page on My Te Papa!</p>

<footer class="footer">
  <div class="row">
    <div class="col-xs-4">
    </div><div class="col-xs-4">
    	<span class="glyphicon glyphicon-home"></span> <%= link_to "Home", root_path %>
    </div><div class="col-xs-4">
    </div>
</footer>

app/views/static_pages/home.html.erb
<h1><%= image_tag('logo.png', size: '150x150') %></h1>
<h1 class="main-title" style="margin-bottom: 0px;">Te Papa<br />Companion</h1><br />
<h3 class="sub-title" style="margin-top: 0px;">Your all-in-one tour guide as you dive into culture, history and art!</h3>

<center><%= link_to "View the Exhibits", levels_path, class: "btn btn-lg btn-green" %></center>

<footer class="footer">
	<div class="row">
		<div class="col-xs-4">
			<span class="glyphicon glyphicon-info-sign"></span> <%= link_to "About", about_path %>
		</div><div class="col-xs-4">
		<span class="glyphicon glyphicon-user"></span> 
		<% if logged_in? %>
		<%= link_to "Profile", current_user %>
		<% else %>
		<%= link_to "Log In", login_path %>
		<% end %>
	</div><div class="col-xs-4">
	<span class="glyphicon glyphicon-question-sign"></span> <%= link_to "Help", help_path %>
</div>
</footer>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row user-exhibits">
	<div class="col-md-3">
		<div class="user-details">
			<center><%= gravatar_for @user %></center>
			<h1 style="margin-top: 0px"><%= @user.name %></h1>
		</div>
	</div>

	<h1>Saved Displays</h1>
	<div class="col-md-9">
		<div class="exhibit-block">
			<%= link_to 'Black Beech', display_page_path('mountainstosea', 'blackbeech'), class: "btn btn-wide btn-green" %>
			<p style="margin-top: 10px;">Walking through a beech forest on a sunny day with dappled sunlight filtering through the canopy overhead...</p>
		</div>

		<div class="exhibit-block">
			<%= link_to 'Pygmy Blue Whale', display_page_path('mountainstosea', 'pygmybluewhale'), class: "btn btn-wide btn-green" %>
			<p style="margin-top: 10px;">The suspended skeleton in Mountains to the Sea comes from a whale which was hit by a container ship off the...</p>
		</div>

		<div class="exhibit-block">
			<%= link_to 'Giant Weta', display_page_path('awesomeforces', 'giantweta'), class: "btn btn-wide btn-green" %>
			<p style="margin-top: 10px;">Imagine climbing up forest trees to set bird traps or to forage for fruits, and disturbing a wetapunga in...</p>
		</div>

		<div class="exhibit-block">
			<%= link_to 'Cecil Malthus', display_page_path('gallipoli', 'cecilmalthus'), class: "btn btn-wide btn-green" %>
			<p style="margin-top: 10px;">One of the most arresting sights in Gallipoli: The scale of our war is the final giant sculpture of Cecil...</p>
		</div>

		<div class="exhibit-block">
			<%= link_to 'Private Jack Dunn', display_page_path('gallipoli', 'jackdunn'), class: "btn btn-wide btn-green" %>
			<p style="margin-top: 10px;">This is the fourth blog in our series about the real people behind the larger-than-life sculptures featured...</p>
		</div>
	</div>
</div>

<footer class="footer">
  <div class="row">
    <div class="col-xs-4">
    	<span class="glyphicon glyphicon-home"></span> <%= link_to "Home", root_path %>
    </div><div class="col-xs-4">
      	<span class="glyphicon glyphicon-lock"></span> <%= link_to "Log Out", logout_path, method: "delete" %>
    </div><div class="col-xs-4">
    	<span class="glyphicon glyphicon-question-sign"></span> <%= link_to "Help", help_path %>
    </div>
</footer>